---
# file: group_vars/all
centos_yum_mirror: mirrors.ustc.edu.cn
pypi_mirror:
  args: '--upgrade --index-url https://mirrors.ustc.edu.cn/pypi/web/simple'
#  _  __     _                          _
# | |/ /    | |                        | |
# | ' /_   _| |__   ___ _ __ _ __   ___| |_ ___  ___
# |  <| | | | '_ \ / _ \ '__| '_ \ / _ \ __/ _ \/ __|
# | . \ |_| | |_) |  __/ |  | | | |  __/ ||  __/\__ \
# |_|\_\__,_|_.__/ \___|_|  |_| |_|\___|\__\___||___/
#
#
kube_version: v1.10.5
token: b0f7b8.8d1767876297d85c

# 1.8.x feature: --feature-gates SelfHosting=true
init_opts: ""

# Any other additional opts you want to add..
kubeadm_opts: ""
# For example:
# kubeadm_opts: '--apiserver-cert-extra-sans "k8s.domain.com,kubernetes.domain.com"'

service_subnet: 10.96.0
service_cidr: "{{ service_subnet }}.0/12"
dns_name: cluster.local
dns_ip: "{{ service_subnet }}.10"

# Network implementation('flannel', 'calico')
network: flannel
pod_network_cidr: "10.244.0.0/16"
cni_opts: "--iface=ens33" # flannel: --iface=eth1, calico: interface=eth1

enable_dashboard: yes

# A list of insecure registrys you might need to define
#insecure_registrys: ""
# insecure_registrys: ['gcr.io']

systemd_dir: /lib/systemd/system
system_env_dir: /etc/sysconfig
network_dir: /etc/kubernetes/network
kubeadmin_config: /etc/kubernetes/admin.conf
kube_addon_dir: /etc/kubernetes/addon

search_domain: cluster.local
# Registry for docker tag
target_registry: registry.cluster.local
# Your private registry
origin_registry: registry.cluster.local
# Keep it if you in People's Republic of China
special_registry: k8s.gcr.io
docker_images:
  - kube-apiserver-amd64:v1.10.5
  - kube-controller-manager-amd64:v1.10.5
  - kube-scheduler-amd64:v1.10.5
  - kube-proxy-amd64:v1.10.5
  - k8s-dns-dnsmasq-nanny-amd64:1.14.8
  - pause-amd64:3.1
  - etcd-amd64:3.1.12
  - coredns:1.1.3
  - kubernetes-dashboard-amd64:v1.8.3
  - k8s-dns-kube-dns-amd64:1.14.8
  - k8s-dns-sidecar-amd64:1.14.8