---

- name: Join to Kubernetes cluster
  shell: |
    kubeadm join --skip-preflight-checks \
                 --token {{ token }} \
                 {{ groups['masters'][0] }}:6443 \
                 --discovery-token-unsafe-skip-ca-verification
  register: join_cluster

- name: Enable and restart kubelet engine
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes
  register: started_kubelet